baseurl: '/'
permalink: pretty
title: 'VietnamMUN.org'

logo:
  mobile: "images/favicon-32x32.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/favicon-256x256.svg"
  desktop_height: "100px"
  desktop_width: "100px"

home: 
  limit_projects: 3
  # only excerpt up to here
  excerpt_separator: <!--break-->
  show_excerpts: true

collections:
  projects:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
